import { providers } from './js/providers.js?v=2';

const $=s=>document.querySelector(s); const state={data:{},mapMode:'weather',refreshAt:Date.now()+300000};
const weatherLabel=code=>({0:'Despejado',1:'Mayormente despejado',2:'Parcialmente nublado',3:'Nublado',45:'Niebla',51:'Llovizna',61:'Lluvia',80:'Chubascos',95:'Tormenta'}[code]||'Condición variable');
const weatherIcon=code=>code<=1?'☀️':code<=3?'🌤️':code>=51?'🌧️':'☁️';
const formatTime=value=>value?new Date(value).toLocaleString('es-PE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const badgeFor=d=>d.status==='available'?(d.isDemo?['DEMO','demo']:['REAL','real']):d.status==='stale'?['CACHÉ','warn']:['NO DISP.','off'];
const card=(key)=>document.querySelector(`[data-card="${key}"]`);
const setCard=(key,html)=>{const el=card(key),d=state.data[key],badge=badgeFor(d);el.querySelector('.card-body').classList.remove('skeleton');el.querySelector('.card-body').innerHTML=html;el.querySelector('.data-badge').textContent=badge[0];el.querySelector('.data-badge').className=`data-badge ${badge[1]}`;el.querySelector('footer').innerHTML=`<span>${d.sourceName}</span><time>${formatTime(d.lastUpdated)}</time>`;};
const unavailable=d=>`<div class="unavailable"><b>${d.note}</b><span>${d.error||'No se publicarán datos inventados.'}</span></div>`;
const demoNote=d=>d.isDemo?`<p class="data-note">Dato demostrativo</p>`:'';

function renderCards(){
  const e=state.data.exchangeRate;let exHtml=unavailable(e);if(e.data){const h=e.data.history?.length?e.data.history:[e.data.sell];const mn=Math.min(...h),mx=Math.max(...h),span=(mx-mn)||1,step=h.length>1?120/(h.length-1):0;const pts=h.map((v,i)=>`${(i*step).toFixed(1)},${(33-((v-mn)/span)*28).toFixed(1)}`).join(' ');const v=e.data.variation||0,up=v>=0,arrow=v>0?'▲':v<0?'▼':'■';exHtml=`<div class="exchange"><p><small>Compra</small><strong>S/ ${e.data.buy.toFixed(3)}</strong></p><p><small>Venta</small><strong>S/ ${e.data.sell.toFixed(3)}</strong></p></div><div class="variation"><span><small>Variación</small><b class="${up?'up':'down'}">${arrow} ${Math.abs(v)}%</b></span><svg viewBox="0 0 120 35"><polyline points="${pts}"/></svg></div>${demoNote(e)}`;}setCard('exchangeRate',exHtml);
  const w=state.data.weather;setCard('weather',w.data?`<div class="weather-now"><strong>${Math.round(w.data.temp)}°C</strong><span>${weatherIcon(w.data.weatherCode)}</span><p><b>${w.data.city}</b>${weatherLabel(w.data.weatherCode)}<small>Humedad: ${w.data.humidity}%<br>Viento: ${w.data.wind}</small></p></div><div class="forecast">${w.data.forecast.map((f,i)=>`<span><small>${i?'Día '+(i+1):'Hoy'}</small>${Math.round(f.max)}° / ${Math.round(f.min)}° ${weatherIcon(f.code)}</span>`).join('')}</div>`:unavailable(w));
  const q=state.data.earthquakes;setCard('earthquakes',q.data?`<div class="quake-data"><p><small>Magnitud</small><strong>${q.data.magnitude.toFixed(1)}</strong></p><p><small>Profundidad</small><b>${q.data.depth}</b><small>Ubicación</small><b>${q.data.location}</b></p><i class="target"></i></div>`:unavailable(q));
  const a=state.data.agriculture;setCard('agriculture',a.data?`<div class="mini-table"><div class="table-head">Producto <span>Unidad</span><span>Precio S/</span><span>Var. 24 h</span></div>${a.data.map(r=>`<div><b>${r.product}</b><span>${r.unit}</span><span>${r.price.toFixed(2)}</span><span class="${r.variation<0?'down':'up'}">${r.variation<0?'▼':'▲'} ${Math.abs(r.variation)}%</span></div>`).join('')}</div>${demoNote(a)}`:unavailable(a));
  const m=state.data.maritime;setCard('maritime',m.data?`<h3>${m.data.title}</h3><div class="marine"><p><small>Nivel</small><strong>${m.data.level}</strong><i>≈</i></p><p><b>${m.data.coast}</b>${m.data.waves}<small>Vigencia<br>${m.data.validity}</small></p></div>${demoNote(m)}`:unavailable(m));
  const n=state.data.elPeruano;setCard('elPeruano',n.data?n.data.map(item=>`<a href="${item.url||n.sourceUrl}" target="_blank" rel="noreferrer"><span>▧</span><p><b>${item.type}</b><small>${item.title}</small></p><time>${item.date}</time></a>`).join('')+demoNote(n):unavailable(n));
}

const cities=[{n:'Tumbes',lon:-80.45,lat:-3.57},{n:'Piura',lon:-80.63,lat:-5.19},{n:'Chiclayo',lon:-79.84,lat:-6.77},{n:'Trujillo',lon:-79.03,lat:-8.11},{n:'Lima',lon:-77.04,lat:-12.05},{n:'Huancayo',lon:-75.20,lat:-12.07},{n:'Cusco',lon:-71.97,lat:-13.52},{n:'Arequipa',lon:-71.54,lat:-16.40},{n:'Tacna',lon:-70.25,lat:-18.01}];
const bounds={minLon:-81.55,maxLon:-68.5,minLat:-18.5,maxLat:.1};const project=(lon,lat)=>({x:24+((lon-bounds.minLon)/(bounds.maxLon-bounds.minLon))*330,y:24+((bounds.maxLat-lat)/(bounds.maxLat-bounds.minLat))*500});
async function renderMap(){const geo=await (await fetch('./data/peru.geojson')).json();const d=geo.geometry.coordinates.map(r=>r.map(([lon,lat],i)=>{const p=project(lon,lat);return`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`}).join(' ')+' Z').join(' ');$('#peru-shape').setAttribute('d',d);const quake=state.data.earthquakes?.data;const event=quake&&project(quake.lon,quake.lat);$('#city-points').innerHTML=cities.map(c=>{const p=project(c.lon,c.lat),active=state.mapMode==='weather'&&c.n==='Lima';return`<g class="city ${active?'active':''}" transform="translate(${p.x.toFixed(1)} ${p.y.toFixed(1)})"><circle r="${active?10:5}"/><circle r="2"/><text x="${p.x<150?-9:9}" y="4" text-anchor="${p.x<150?'end':'start'}">${c.n}</text></g>`}).join('')+(state.mapMode==='earthquakes'&&event?`<g class="event-point" transform="translate(${event.x} ${event.y})"><circle r="13"/><circle r="4"/></g>`:'');}

const sourceMeta=[['BCRP','Banco Central de Reserva','bcrp','BCR'],['SENAMHI / OPEN-METEO','Meteorología','weather','☀'],['IGP / USGS','Sismos','earthquakes','IGP'],['MIDAGRI','Desarrollo agrario','agriculture','♧'],['DHN','Hidrografía','maritime','⚓'],['SMV','Mercado de valores','smv','SMV'],['BVL','Bolsa de Lima','bvl','BVL'],['EL PERUANO','Diario Oficial','elPeruano','EP']];
function renderSources(){let active=0;$('#source-grid').innerHTML=sourceMeta.map(([name,desc,key,icon])=>{const d=state.data[key],on=d&&(d.status==='available'||d.status==='stale');if(on)active++;return`<a href="${d?.sourceUrl||'#'}" target="_blank" rel="noreferrer" class="source ${on?'on':'off'}"><i>${icon}</i><p><b>${name}<em></em></b><small>${desc}</small></p></a>`}).join('');$('#sources-count').textContent=`${active} / 8`;}

function answer(key){const d=state.data;const answers={summary:`Resumen: ${badgeFor(d.weather)[0]} en clima, ${badgeFor(d.earthquakes)[0]} en sismos y ${badgeFor(d.exchangeRate)[0]} en tipo de cambio.`,weather:d.weather.data?`Clima real en Lima: ${Math.round(d.weather.data.temp)} °C, ${weatherLabel(d.weather.data.weatherCode).toLowerCase()}, humedad ${d.weather.data.humidity}%.`:'Fuente meteorológica no disponible temporalmente.',earthquakes:d.earthquakes.data?`Último evento real del proveedor ${d.earthquakes.sourceName}: magnitud ${d.earthquakes.data.magnitude.toFixed(1)}, ${d.earthquakes.data.location}.`:'Fuente sísmica no disponible temporalmente.',exchangeRate:d.exchangeRate.data?`Tipo de cambio referencial de mercado (USD/PEN): compra S/ ${d.exchangeRate.data.buy.toFixed(3)} y venta S/ ${d.exchangeRate.data.sell.toFixed(3)}. No es el oficial SUNAT.`:'Fuente de tipo de cambio no disponible temporalmente.',agriculture:`Precios demostrativos: ${d.agriculture.data.map(x=>`${x.product} S/ ${x.price.toFixed(2)}`).join(', ')}.`};const bubble=$('#assistant-message');bubble.innerHTML=`<b>Radar Perú IA</b><span>${answers[key]||'Solo puedo ayudarte con información del panel Radar Perú IA: normas, finanzas, clima, agro, marina, bolsa y sismos.'}</span><time>${new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})}</time>`;}

async function refresh(){const btn=$('#refresh-btn');btn.classList.add('loading');document.querySelectorAll('.data-badge').forEach(x=>{x.textContent='CARGANDO';x.className='data-badge'});const entries=await Promise.all(Object.entries(providers).map(async([key,provider])=>[key,await provider()]));state.data=Object.fromEntries(entries);renderCards();renderSources();await renderMap();const now=new Date();$('#last-review').textContent=now.toLocaleString('es-PE',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});state.refreshAt=Date.now()+300000;btn.classList.remove('loading');}
document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.query)));document.querySelectorAll('[data-map]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-map]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mapMode=b.dataset.map;renderMap();}));$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const value=$('#chat-input').value.toLowerCase();const key=value.includes('clima')?'weather':value.includes('sismo')?'earthquakes':value.includes('cambio')?'exchangeRate':value.includes('agro')?'agriculture':null;answer(key);$('#chat-input').value='';});$('#refresh-btn').addEventListener('click',refresh);setInterval(()=>{const seconds=Math.max(0,Math.ceil((state.refreshAt-Date.now())/1000));$('#refresh-countdown').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds===0)refresh();},1000);refresh();
